#!/usr/bin/env Rscript
needsMan <- NULL
for (f in list.files("R", full.names=TRUE)) {
  if (f!="R/utils.R") {
    raw <- grep("function(", readLines(f), fixed=TRUE, value=TRUE)
    needsMan <- c(needsMan, breheny::splitleft(raw, " <- "))
  }
}
hasMan <- breheny::splitleft(list.files("man"), ".Rd")

# Skeleton
skeleton <- "\\name{FUN}
\\alias{FUN}
\\title{Reproduce CLASS NUM}
\\usage{
USAGE
}
\\description{
\\code{FUN()} will recreate CLASS NUM from the book.  If you specify any
options, your results may look different.  See the code for details.
}
\\arguments{
ARGS
}
\\examples{
FUN()
}"

breheny::source.dir("R")
for (x in setdiff(needsMan, hasMan)) {
  CLASS <- ifelse(substr(x,1,1)=="F", "Figure", "Example")
  NUM <- gsub("Ex", "", gsub("Fig", "", x))
  man <- gsub("FUN", x, skeleton)
  man <- gsub("CLASS", CLASS, man)
  man <- gsub("NUM", NUM, man)
  USAGE <- prompt(name=x, file=NA)$usage
  man <- gsub("USAGE", USAGE[2:(length(USAGE)-2)], man)
  ARGS <- prompt(name=x, file=NA)$arguments
  ARGS <- gsub("  \\item{n}{\n%%     ~~Describe \\code{n} here~~\n}",
               "  \\\\item{n}{Sample size}\n", ARGS, fixed=TRUE)
  ARGS <- gsub("  \\item{N}{\n%%     ~~Describe \\code{N} here~~\n}",
               "  \\\\item{N}{Number of simulated realizations}\n", ARGS, fixed=TRUE)
  ARGS <- gsub("  \\item{p}{\n%%     ~~Describe \\code{p} here~~\n}",
               "  \\\\item{p}{Number of features}\n", ARGS, fixed=TRUE)
  ARGS <- gsub("  \\item{seed}{\n%%     ~~Describe \\code{seed} here~~\n}",
               "  \\\\item{seed}{Random seed}\n", ARGS, fixed=TRUE)
  ARGS <- gsub("  \\item{out}{\n%%     ~~Describe \\code{out} here~~\n}",
               "  \\\\item{out}{Output of Example}\n", ARGS, fixed=TRUE)
  man <- gsub("ARGS", paste(ARGS[2:(length(ARGS)-1)], collapse="\n"), man)
  writeLines(man, paste0("man/", x, ".Rd"))
}
